### ISSUE TITLE
Increase the timeout before hiding stale results.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#122]
We currently allow stale recommendations to be shown for up to 50ms, to allow time for new recommendations to come in, preventing an unsightly highlight flash and some UI jank. Under the current deployment—without HTTP/2, a CDN, or an upstream cache—this is not enough. Let's increase it to a reasonable number—100-150ms should be fine—until we have a little more speed.

![giphy](https://cloud.githubusercontent.com/assets/23885/14154657/e09a4640-f67a-11e5-94c0-f805158180ea.gif)

When this is merged, file a bug to revert this change once that happens.

**Comment by ghost** [comment]
Before we move forward on this we're waiting on what kind of numbers we see from our proxy.

**Comment by chuckharmston** [comment]
From my machine, I ran a short test to get the response time of 1000 queries using the following:

``` bash
run() {
    number=$1
    shift
    for i in `seq $number`; do
      $@
    done
}
run 100 curl -o /dev/null -s -w %{time_total}\\n  https://universalsearch.testpilot.firefox.com/\?q\=f\
```

Mean response time: 318.42ms
Standard deviation: 30.61ms
High: 440ms
Low: 256ms

This is pretty slow—consistently slow—especially given my internet connection speed:

![screen shot 2016-04-26 at 12 06 23 pm](https://cloud.githubusercontent.com/assets/23885/14829159/545eded8-0ba7-11e6-8873-c4952361de01.png)

**Comment by chuckharmston** [comment]
I also confirmed that we are not using HTTP/2.0 in responses. That would help these numbers immensely.

**Comment by chuckharmston** [comment]
Coincidentally, nginx 1.10 was promoted to stable today, featuring HTTP/2.0 support: http://nginx.org/en/CHANGES-1.10

**Comment by ghost** [comment]
@mostlygeek -- do we have http/2.0 enabled on nginx?  I think that was the plan we talked about

**Comment by mostlygeek** [comment]
We don't have http/2 enabled on nginx. 

Here's a list off the top of my head for things to optimize and how to get the best performance:
- http1 => http2:  Removes TLS handshake overhead since we can reuse a connection. More complex to implement server side and few CDNs offer it.
- caching: the right balance between freshness and cacheability. It's currently 1 week. Very good for performance, not so good for freshness. 
- CDNs - to reduce client => POP latency globally. Might save 5ms to 10ms but need to test the value of this.

I did some testing on the shared wifi in a coffee shop: 

``` bash
$ for i in $(seq 10); do curl -o /dev/null -s -w "%{time_connect} %{time_appconnect} %{time_starttransfer}\n" https://universalsearch.testpilot.firefox.com/__lbheartbeat__ | awk '{app=$3-$2; tls=$2-$1} END {printf "network: %sms, tls: %sms, app: %sms\n", $1*1000, tls*1000, app*1000}'; done
network: 537ms, tls: 104ms, app: 15ms
network: 18ms, tls: 104ms, app: 15ms
network: 18ms, tls: 105ms, app: 15ms
network: 18ms, tls: 106ms, app: 15ms
network: 18ms, tls: 111ms, app: 15ms
network: 17ms, tls: 107ms, app: 14ms
network: 18ms, tls: 102ms, app: 15ms
network: 17ms, tls: 105ms, app: 15ms
network: 18ms, tls: 104ms, app: 15ms
network: 19ms, tls: 105ms, app: 15ms
```
- `network` - time to make the TCP connection
- `tls` - time to do the tls handshake/connection
- `app` - time for the app to do something and start sending data

Here's google.ca as a comparison: 

``` bash
$ for i in $(seq 10); do curl -o /dev/null -s -w "%{time_connect} %{time_appconnect} %{time_starttransfer}\n" https://www.google.ca | awk '{app=$3-$2; tls=$2-$1} END {printf "network: %sms, tls: %sms, app: %sms\n", $1*1000, tls*1000, app*1000}'; done
network: 69ms, tls: 87ms, app: 52ms
network: 7ms, tls: 78ms, app: 48ms
network: 7ms, tls: 184ms, app: 49ms
network: 7ms, tls: 78ms, app: 51ms
network: 6ms, tls: 82ms, app: 46ms
network: 7ms, tls: 78ms, app: 53ms
network: 9ms, tls: 77ms, app: 41ms
network: 7ms, tls: 92ms, app: 45ms
network: 7ms, tls: 79ms, app: 51ms
network: 8ms, tls: 79ms, app: 52ms
```

I would say the lowest hanging fruit would be to look at moving the TLS overhead. Perhaps going to http/2 we make a single tls connection and reuse it. This is a longer design discussion as it's a non trivial change to make.

**Comment by chuckharmston** [comment]
I absolutely agree that moving the TLS overhead is a great start. In fact, our addon is already warming the connection in anticipation of H/2: https://github.com/mozilla/universal-search/blob/master/lib/recommendation-server.js#L66-L80

**Comment by jaredhirsch** [comment]
I'll bump the timeout to 100ms, and we'll see how it feels
