### ISSUE TITLE
Show special cards for searches recognized as movies.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#200]
Blocked on https://github.com/mozilla/universal-search-recommendation/issues/134

To be defined:
- [x] To what priority do we give movie hits relative to wikipedia or TLDs? (Probably: higher than each. @nchapman to confirm) 
- [x] What does it look like? (@bryanbell to come in with a design. Assigning to him)

**Comment by chuckharmston** [comment]
TLD > Movie > Wikipedia

**Comment by jaredhirsch** [comment]
Copying over @bryanbell's mock from https://github.com/mozilla/universal-search-recommendation/issues/134:

---

![rec - movie - captain](https://cloud.githubusercontent.com/assets/228979/15308052/038879b4-1b8e-11e6-9d02-28edc573b272.png)

**Comment by jaredhirsch** [comment]
Here's where we'll have to leave it for a few weeks:

<img width="693" alt="screen shot 2016-05-27 at 5 06 05 pm" src="https://cloud.githubusercontent.com/assets/96396/15623759/5ec55a84-242d-11e6-9ccd-54f46043a023.png">

Highlighted:

<img width="696" alt="screen shot 2016-05-27 at 5 06 20 pm" src="https://cloud.githubusercontent.com/assets/96396/15623758/5ec365bc-242d-11e6-9172-573cef346d20.png">

The card looks ready to go, but I haven't had enough time to do a final cleanup pass, particularly on the CSS--we should probably only use XUL's box model, as mixing in HTML5 flexbox CSS properties is a recipe for madness. Blake suggested only using attributes for the weirdo XUL box model `pack` and `align` properties (these are currently also used via their CSS equivalents, `-moz-box-pack` and `-moz-box-align`). Code is stashed in the wip-movie-card branch on my fork for now. Also, our existing code increases the minimum width of the popup, but I think we should stop doing that, because the built-in popup does not grow its width to fit its content, and the width can jump around on a narrow window.

Here are some screenshots of native behavior and our recommendation UI on release channel (46.0.1):

1) Note that the Firefox native popup behavior is to never stretch past the boundaries of the urlbar. On dev edition/nightly it's similar, except the bounds are the window.

<img width="334" alt="screen shot 2016-05-27 at 4 45 41 pm" src="https://cloud.githubusercontent.com/assets/96396/15623662/b3891918-242b-11e6-93eb-68f0f72a7960.png">

2) Here's how our popup performs at narrow widths--I think it would be best to not change the popup's width here, and also ellipsize content like the other results.

<img width="354" alt="screen shot 2016-05-27 at 4 44 58 pm" src="https://cloud.githubusercontent.com/assets/96396/15623658/b2ebec4c-242b-11e6-9f69-d4483e47f17a.png">
<img width="336" alt="screen shot 2016-05-27 at 4 45 37 pm" src="https://cloud.githubusercontent.com/assets/96396/15623661/b3640100-242b-11e6-8ec3-c7936b0085b8.png">

3) Here's how the recommendation looks at very generous widths. I'm not a huge fan of the one long line of text, but if we don't set the plot summary to 100% width, the URL tends to sneak up onto the end of the line. Reminds me of a float clearing bug, but it's some XUL oddity.

<img width="1169" alt="screen shot 2016-05-27 at 4 45 18 pm" src="https://cloud.githubusercontent.com/assets/96396/15623659/b30df530-242b-11e6-8ac0-9a12e0df74b8.png">
<img width="1147" alt="screen shot 2016-05-27 at 4 45 28 pm" src="https://cloud.githubusercontent.com/assets/96396/15623660/b340084a-242b-11e6-86df-226c3e409ad7.png">
