### ISSUE TITLE
Search Bar not Restored on Uninstall when Tab Center is installed

### ISSUE THREAD

**Issue by mlennon3** [mozilla/universal-search#216]
Possible duplicate of #195, but that issue is closed.

I cannot get my search bar back after installing and uninstalling universal-search via Test Pilot.  FF 46.0.1 on OSX 10.11.4.

**Comment by jaredhirsch** [comment]
@mlennon3 do you also have tab center installed?

**Comment by mlennon3** [comment]
I don't have any TP experiments enabled, I have even uninstalled Test Pilot, but that doesn't help to get back the search bar either

**Comment by jaredhirsch** [comment]
mlennon3: OK, at the time you first noticed the bug, what TxP experiments did you have installed? 

There's a [known bug](https://github.com/bwinton/VerticalTabs/issues/50) affecting search uninstallation when you have Tab Center installed. I suspect that bug's not fixed, based on the number of broken customization reports here and in the Tab Center repo.

**Comment by mlennon3** [comment]
Hm, yes the two experiments I installed with TxP were Tab center and Universal Search.  What would I have to do to get FF back to normal?

**Comment by jaredhirsch** [comment]
mlennon3: Great! The bug is that Tab Center breaks the CustomizationUI code, which is what this add-on uses to clean up after itself when uninstalling. The fix is to uninstall tab center, then open up the Customize panel (View > Toolbars > Customize), and drag the search bar back to where you'd like to have it. 

Closing, please feel free to reopen if you continue to have trouble.

Related to https://github.com/bwinton/VerticalTabs/issues/50

**Comment by mlennon3** [comment]
Thanks :)
