### ISSUE TITLE
Handle User Defined Search Engines

### ISSUE THREAD

**Issue by BenjaminHCCarr** [mozilla/universal-search#223]
I understand that this is a pre-populated (it appears) list of common terms, but it would be nice if we could use other engines, ala DuckDuckGo, etc.

InstantFox may be something to look at:
[https://github.com/estivo/Instantfox/blob/master/firefox/chrome/content/defaultPluginList.js](https://github.com/estivo/Instantfox/blob/master/firefox/chrome/content/defaultPluginList.js)

I would rather not use BING, and it looks like you are working on Alexa and WIkipedia heavily at the moment: 
[https://github.com/mozilla/universal-search-recommendation](https://github.com/mozilla/universal-search-recommendation)

One of my primary uses is google scholar, is there a way (I can't code this) to implement an API to use the "suggested" additional search engines in:
[https://addons.mozilla.org/en-US/firefox/search/?atype=4](https://addons.mozilla.org/en-US/firefox/search/?atype=4)

I realize this is in TestPilot for a reason, and while caching searches is nice (I am sure "Prince" would have helped a couple weeks ago) expanding the API to allow importing of already available plugins, even if we had to import and tailor them and do a PR. I used to write search plugins for the old "Mycroft" project, even hosting something like that where people could implement additional options would be great.

**Comment by jaredhirsch** [comment]
@BenjaminHCCarr Hi! We currently fetch recommendations from the server, so the simplest way to customize what you see in your browser would be to fork [the recommendation server](https://github.com/mozilla/universal-search-recommendation) and hack on that. You can set your browser to use a local recommendation engine in the add-on's preferences.

InstantFox supports a choice of **search suggestion** APIs (turning 'f' into 'facebook', for example), and that's something we could support easily, since those are all public APIs. However, the recommendation is generated by sending the top search suggestion to a web search API, and there aren't many general web search APIs right now, just Yahoo (deprecated / future unclear) and Bing. Incidentally, DDG is also built on top of Yahoo's BOSS API, presumably they, too, are making a special deal with Yahoo or migrating to Bing.

Opened #232 to capture the idea of sending the user's suggestion service preference to the server.

Finally, note that Google Scholar doesn't provide an API, so there's not much integration possible without resorting to scraping results pages. Thanks for the suggestions, and for trying out universal search :-)

Closing. Please comment if I've missed anything
