### ISSUE TITLE
Disabling Universal Search breaks some buttons all over the internet

### ISSUE THREAD

**Issue by jpetto** [mozilla/universal-search#229]
- Operating System: OS X 10.11.5
- Firefox build: Release 46.0.1
- Non Test Pilot Add-ons: [JSON-formatter](https://addons.mozilla.org/en-US/firefox/addon/json-formatter/), [User Agent Switcher](https://addons.mozilla.org/en-US/firefox/addon/user-agent-switcher/)
## Initial issue

After disabling Universal Search and opening the associated survey, the "Next" button at the bottom of the survey was completely inert. No console error messages, no UI error messages, nothing. Disabled Tracking Protection for the survey domain, but same results. Re-enabled and disabled Universal Search after restarting browser and issue remained.
## Subsequent issues

Later the same day and into the next (today), seemingly random buttons on the internet stopped working. I tried to remove an item from my [Finish Line](http://www.finishline.com) cart and the "Remove Item" button didn't work. I thought maybe it was Tracking Protection, but disabling had no positive effects. Experienced the same issue when trying to log in to [Geico](https://www.geico.com/), Google Docs via Okta (the screen where it shows your security image), and when trying to submit a new GitHub issue. Same experience in all cases - no console errors, no UI errors, refreshing the page did not help.

After the Okta failure, I began to suspect Test Pilot was the culprit. I disabled Activity Stream and tried again with the same failures. I disabled Tab Center, same failures. I then disabled Test Pilot entirely, and suddenly all the buttons worked again.

After a few hours, I re-enabled Tracking Protection and Test Pilot with Activity Stream and Tab Center, and all buttons mentioned above work as expected.
## Reproducing

I just re-enabled Universal Search, restarted Firefox, then disabled Universal Search, and the issue above returned. Seems like there's a nasty side-effect to disabling Universal Search?

**Comment by jaredhirsch** [comment]
@jpetto Hi! None of the code in Universal Search has any impact on the content of pages displayed by Firefox, nor does the code change any prefs or touch any code related to security / tracking protection. Your problems with on-page javascript sound like you're using an ad blocker or have custom third-party cookie settings configured in Firefox.

Universal Search modifies the address bar and its dropdown menu, so I could see breakage related to address bar navigation, or the dropdown being empty or showing stale results--this is the sort of breakage I've seen when developing on my machine.

The broken 'next' button on the survey is a known issue (https://github.com/mozilla/testpilot/issues/856) that's likely due to Firefox blocking third-party scripts (in that case, Survey Gizmo JS that's used to submit the form). As I mentioned above, I really think it's third-party script settings causing problems on other pages.

I'm curious what you mean by "the issue above" here:

> I just re-enabled Universal Search, restarted Firefox, then disabled Universal Search, and the issue above returned. Seems like there's a nasty side-effect to disabling Universal Search?

Did you mean the problems with the survey, or problems on other websites?

Let's try to chat about this in IRC sometime and see if you can reproduce with a fresh profile / default settings. I'll leave this open for now, and we'll see if anyone else reports similar issues.

**Comment by jpetto** [comment]
To sum up our IRC chat/testing, I did the following to reproduce the problem:
- Created a new Firefox profile
- Launched Fx release using the new profile
- Installed TestPilot
- Enabled all three features: Tab Center, Activity Stream, Universal Search
- Disabled Universal Search
- Tested buttons on various websites:
  - [finishline.com](http://finishline.com) - Add items to your cart, go to cart page, click "X" to remove an item. Clicking the "Remove Item" button does nothing
  - [geico.com](https://www.geico.com) - Hover over the "Log in" icon in the top right nav to expose login form. Clicking "Log in" button does nothing (regardless of credentials entered).
  - [github.com](https://www.github.com) - Attempt to sign up for an account on the home page. The "Sign Up" button does nothing.

I was able to fix the issue by going to Tools > Add-ons, disabling TestPilot, Tab Center, and Activity Stream, then restarting the browser.

**Comment by jaredhirsch** [comment]
@jpetto Thanks for this detailed bug report, and for discussing this bug with me in IRC yesterday. I'm going to dupe this to #213, which is a slightly earlier report of some other content buttons breaking. If you see additional breakage with this addon in a fresh profile, please add comments to #213.
