### ISSUE TITLE
Universal Search removes Regular Search bar upon every restart

### ISSUE THREAD

**Issue by tysox** [mozilla/universal-search#249]
Universal Search is great, but occasionally I want to specifically search for a term in e.g. Google Scholar or Wolfram|Alpha; so I want to keep the search bar visible.
Universal Search is getting rid of the search bar upon every restart, meaning I need to 'customise' my browser window each time. Is there a way to remove this, so that it gets rid of it upon install, but doesn't try to again after that?

**Comment by chuckharmston** [comment]
The specific implementation you requested is not actually possible; add-ons have to modify browser windows as they're opened, rather than having just one thing to do on install. 

However, we absolutely should provide a way for users to search with secondary search engines. I've filed a new issue for that consideration here: https://github.com/mozilla/universal-search/issues/259

Thanks for the feedback!
