### ISSUE TITLE
Search for common application extensions (*.json, *.exe, etc) attempts to redirect to webpage

### ISSUE THREAD

**Issue by acmiyaguchi** [mozilla/universal-search#257]
When I attempt to search for application extensions, I get redirected to a server not found. I would like to be able to search my through my default search provider for things like *.json without it being interpreted as a valid domain extension.

You can reproduce by searching something like `node.js` in the universal search bar, which should redirect you to a `Server not found` page. This should instead go to a search page for `node.js`. This issue is current as of 1.0.6.

**Comment by chuckharmston** [comment]
This is actually by design; to ensure the reliability of our metrics, we change the core Firefox experience as little as possible. In this case, we do not modify how Firefox interprets what looks like a domain at all, which is what's happening here: it's attempting to navigate to [http://node.js](node.js), which does not exist.

As a workaround, you can either surround the string in quotes (i.e. `"node.js"`) or replace the period character with a space (i.e. `node js`) to get the results you're looking for.

Thanks for the report!
