### ISSUE TITLE
'substring' awesome bar recall seems somehow to work less well.

### ISSUE THREAD

**Issue by gregglind** [mozilla/universal-search#271]
To test:
- open some pages from a github project (such as  mozilla/addons-server#1880)
- close them
- open a new window / tab whatever

Type in 'addons'

Expected:  It SHOULD be pulling 'substring' from history.

(Note this may have changed 'recently')

**Comment by chuckharmston** [comment]
@gregglind Can you verify that this behavior doesn't exist with the Universal Search add-on disabled? (Due to mozilla/addons-server#267, you'll want to restart Firefox after disabling to test). In non-release branches, the awesome bar is undergoing some structural changes, so there's a chance the problem lies therein, rather than here.

**Comment by jaredhirsch** [comment]
Hey @gregglind, thanks for filing a bug! We haven't altered any code related to search. All this addon does is sometimes insert a recommendation. We do extend the XBL UI, but I'm not sure how that could be the culprit here--nevertheless, I'll leave this open for a bit to see if it's symptomatic of other dev edition bustage.

**Comment by gregglind** [comment]
Sorry for the delay,
1.  I turned on activity-stream AND tab-center, and turned off U-S
2. Turned off U-S
3.  opened a window.
4.  'middle substring' recall from history now works again.  

I am more confident that it is the U-S addon.

**Comment by jaredhirsch** [comment]
@gregglind The latest version of the search addon might have fixed whatever issues you were seeing. Mind trying again? Current version is 1.0.9

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
