### ISSUE TITLE
Unable to browse the web with Universal Search enabled and latest Nightly

### ISSUE THREAD

**Issue by lissyx** [mozilla/universal-search#286]
_Edited by @6a68: I've broken out some child bugs for individual smaller issues. Crossing them off here as I go, so interested parties can follow progress at a glance._
- [x] #292 
- [x] #293 
- [x] #294 
- [x] #295 
- [x] #296
- [x] #298 

Original bug description follows:

---

Upgraded nightly (linux64, ubuntu 15.10) to latest version (buildid 20160804030441) resulted in address bar not loading anything at all.

STR:
1. Type URL in address bar
2. Press enter or click the load button

Expected:
 Website starts to load

Actual:
 Nothing happens.

I had to disable Universal Search addon to get my nightly back into a working state.

**Comment by lissyx** [comment]
Content of JS Console with Universal Search enabled, while tapping an URL in the address bar, selecting one that matches and pressing enter:

TypeError: Property 'handleEvent' is not callable.(source inconnue)
TypeError: Property 'handleEvent' is not callable.popup.xml:50:15
TypeError: Property 'handleEvent' is not callable.urlbarBindings.xml:939:11
Aborted request for "u".recommendation-server.js:93
TypeError: this.oneOffSearchButtons is null[En savoir plus]urlbarBindings.xml:1665:11
TypeError: Property 'handleEvent' is not callable.(source inconnue)
TypeError: Property 'handleEvent' is not callable.urlbarBindings.xml:939:11
TypeError: Property 'handleEvent' is not callable.urlbarBindings.xml:939:11
Aborted request for "un".recommendation-server.js:93
TypeError: this.oneOffSearchButtons is null[En savoir plus]urlbarBindings.xml:1665:11
TypeError: Property 'handleEvent' is not callable.(source inconnue)
TypeError: Property 'handleEvent' is not callable.urlbarBindings.xml:939:11
TypeError: Property 'handleEvent' is not callable.urlbarBindings.xml:939:11
TypeError: this.oneOffSearchButtons is null[En savoir plus]urlbarBindings.xml:1695:1
Invalid chrome URI: /TypeError: Property 'handleEvent' is not callable.urlbarBindings.xml:939:11
TypeError: Property 'handleEvent' is not callable.popup.xml:134:13
TypeError: this.popup.oneOffSearchButtons is null[En savoir plus]urlbarBindings.xml:370:1
TypeError: Property 'handleEvent' is not callable.urlbarBindings.xml:939:11
TypeError: this.popup.oneOffSearchButtons is null[En savoir plus]urlbarBindings.xml:370:1

**Comment by Work-Parker** [comment]
same issue on my nightly(win10 64 bit) on my latest version( build id: 20160805030444)

when tried recreating I encountered the same issue.

**Comment by jaredhirsch** [comment]
Thanks for the bug reports, all!

I'm going to keep an eye on the Bugzilla bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1180944) for a few more days. If it looks like the patch is going to stick, I'll figure out a fix.

**Comment by jaredhirsch** [comment]
We seem to have at least one major bug at work here, maybe more:

For context, the way this add-on works is by replacing the address bar popup (the dropdown menu that's shown as you type) with a slightly modified popup. XBL is the language used to implement these kinds of interface changes in Firefox, and it's very brittle.
- Minor bug: the Enter button is broken because the one-off search changes added a new element to the base popup (the strip of one-off search options, I guess). This can be fixed by copy-pasting that element into our popup. So, this bug could be easily fixed, but that extra element might cause breakage in release channel Firefox, _and_ the awesomebar popup would still be unusable, because of the major bugs:
- Major bug: the popup is getting drawn as blank and empty after it's shown once. My guess is that it's related to this error: `TypeError: rows[(numRows - 1)] is undefined`. Looks like the way the popup's height is recalculated has changed, and something it expects to be present is not present. Not sure what the fix is here, I'd have to look really closely at how that method has changed.
- Major? bug: each time I type any key in Nightly, I'm seeing `TypeError: Property 'handleEvent' is not callable`. Something in the way we intercept keystrokes, then hand them back to Firefox, is not working. This might be the reason no results are getting shown: maybe Firefox isn't generating suggestions, because it's not getting the keystrokes. I really don't know, though.

Note that I tried disabling the new one-off search pref (`browser.urlbar.oneOffSearches`), which is toggled to `true` in Nightly, and it didn't fix any of these bugs.

_Edit: we're figuring out what to do about this bug, stay tuned._

**Comment by jaredhirsch** [comment]
I'm going to be working on this bug this week

**Comment by 6a68** [comment]
Child bugs: #292, #293, #294, #295, #296

**Comment by jaredhirsch** [comment]
Update: I'm pretty close to a fix, though it requires disabling the one-off search buttons completely. Will likely have to file a followup to re-enable those later.
