### ISSUE TITLE
universal-search always tries to visit an invalid URL if the keyword with a dot

### ISSUE THREAD

**Issue by evanxd** [mozilla/universal-search#302]
Hi Team,

I'm trying to resolve a bug about URL bar module in Firefox, [Bug 1256074](https://bugzilla.mozilla.org/show_bug.cgi?id=1256074) - Always present a 'search' option, even location bar's contents are detected as URLs[1]. Currently, any keyword with a dot will be treated as a URL in Firefox. The bug wants URL bar always to show 'search' option for keywords or URLs.

But I think that might not the best solution for UX enhancement. We should use [Public Suffix List](https://www.publicsuffix.org/list/public_suffix_list.dat)(or any other ways) to detect the string on URL bar is a keyword or an URL. If it's a keyword, do `searchengine` moz-action. If it's a URL, do `visiturl` moz-action.

So here are two questions
1. Will universal-search be a system add-on in Firefox?
2. If so, could we implement that in universal-search add-on rather than [Firefox code base](http://searchfox.org/mozilla-central/source), or we should still implement in Firefox code base?

[Bug 1080682](https://bugzilla.mozilla.org/show_bug.cgi?id=1080682) tries to fix the issue in Firefox code base? But there are still lots of [arguments there](https://bugzilla.mozilla.org/show_bug.cgi?id=1080682#c36), and not progress for the problem yet. It would be great if we can solve the dot problem in universal-search first. Make progresses for the issue, and let universal-search be a system add-on. Make thing happen.

What do you guys think?

**Comment by chuckharmston** [comment]
Hey Evan,

Thanks for the bug! To answer your questions in order:
1. We aren't sure what the outcome of Universal Search will be quite yet. Right now, we're still working on gathering how users interact and engage with the Awesome Bar and our inserted recommendation.
2. It'd likely be best to fix this in Firefox itself. The current ([and future](https://trello.com/b/ojJPAvsU/universal-search)) plans for this add-on are to experiment with the recommendation itself, rather than with other. This may change, but even if so, there's certainly no guarantee that we ever ship a system add-on.

Let me know if you have any further questions!

**Comment by evanxd** [comment]
Hi Chuck,

Got it. Thanks for the reply.
