### ISSUE TITLE
Google logo image is squished

### ISSUE THREAD

**Issue by cpeterso** [mozilla/universal-search#309]
When I type the letter `w` in the address bar, Universal Search suggests google.com. (Why `w` but not `g`? I have no idea.) The Google favicon in the search suggestions looks normal but the larger logo image is squished horizontally. I can't find any other suggestion logos that are squished. I'm using Universal Search version 1.0.9 on Nightly 51.

Here is a screenshot:

![google](https://cloud.githubusercontent.com/assets/629193/18378167/de77f406-765a-11e6-9ea1-b3d00fb64347.png)

**Comment by chuckharmston** [comment]
@cpeterso Could you report back with the body of the request made to the recommendation server? I'm not seeing the squished icon here:

<img width="215" alt="screen shot 2016-09-09 at 1 09 08 am" src="https://cloud.githubusercontent.com/assets/23885/18378401/0d34ace8-762a-11e6-9991-4400a11340f5.png">

The API responses:

https://universalsearch.testpilot.firefox.com/?q=g
https://universalsearch.testpilot.firefox.com/?q=w

The image shown for each: https://logo.clearbit.com/www.google.com

It looks like Google is the result for a search for `w` because one of our partners is suggesting `www.google.com` as the top completed query for it (more on our [methodology](https://github.com/mozilla/universal-search-recommendation/blob/master/docs/methodology.md)). That's...unexpected, but I'm not sure what sort of heuristic we can use to work around that. Maybe ignore results that resemble hostnames?

**Comment by cpeterso** [comment]
I see requests to https://universalsearch.testpilot.firefox.com/?q=g in my browser console, but they don't include the HTTPS response body ("Response body was not stored."). But using an external MITM proxy (Charles Proxy), I don't see the https://universalsearch.testpilot.firefox.com/?q=g requests at all, but I _do_ see universalsearch requests for other letter queries, such as `gg`.

I remembered that I have a keyword search `g` configured for Google. Thinking that might be confusing or short-circuiting Universal Search, I removed that keyword search but nothing changed.

**Comment by cpeterso** [comment]
OK. In a clean profile, I was able to reproduce the squished Google logo and log the https://universalsearch.testpilot.firefox.com/?q=g response. However, the response contains URLs pointing to the expected G logo, so I don't know where the squished Google logo is coming from.

```
{
    "enhancements": {
        "favicon": {
            "color": [
            246,
            243,
            231],
            "url": "https://i.embed.ly/1/image?url=http%3A%2F%2Fwww.google.com%2Fimages%2Fbranding%2Fproduct%2Fico%2Fgoogleg_lodp.ico&key=8c383bd0f96b445088a8e7d39aac0904"
        },
        "tld": "https://logo.clearbit.com/www.google.com",
        "wikipedia": {
            "image": {
                "height": 281,
                "url": "https://i.embed.ly/1/image?url=https%3A%2F%2Fupload.wikimedia.org%2Fwikipedia%2Fcommons%2Fthumb%2Fe%2Fe0%2FGoogle%25E2%2580%2599s_First_Production_Server.jpg%2F170px-Google%25E2%2580%2599s_First_Production_Server.jpg&key=8c383bd0f96b445088a8e7d39aac0904",
                "width": 170
            },
            "title": "Google - Wikipedia, the free encyclopedia",
            "url": "https://en.wikipedia.org/wiki/Google"
        }
    },
    "query": {
        "completed": "google",
        "original": "g"
    },
    "result": {
        "abstract": "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.",
        "title": "Google",
        "url": "http://www.google.com/"
    }
}
```

**Comment by chuckharmston** [comment]
Universal Search [has retired](https://testpilot.firefox.com/experiments/universal-search), so I'm going through and closing old issues.

Thank you for the contribution!
