### ISSUE TITLE
Sometimes recommendation URLs are laid over the "Search with" row.

### ISSUE THREAD

**Issue by chuckharmston** [mozilla/universal-search#81]
Either because the recommendation isn't being fully hidden, or because the "search with" row is overlaying the recommendation row.

<img width="411" alt="75ca6706-e6f2-11e5-8dfe-538fdcf91087" src="https://cloud.githubusercontent.com/assets/23885/13712275/fee3e994-e77f-11e5-97ae-4ba4621f4148.png">

**Comment by jaredhirsch** [comment]
The bug is due to the visibility of the url element [being set to visible](https://github.com/mozilla/universal-search/blob/master/chrome/skin/style.css#L124), so the inherited `visibility:hidden` set on the parent is overridden. (Setting the `collapsed` attribute [is equivalent to](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XUL/Attribute/collapsed) toggling the `visibility` property.)
